services:
  bot:
    container_name: 'webemoji'
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    volumes:
      - .:/app
      - ./daily_stats:/app/daily_stats
      - /TG_FARM:/TG_FARM
